services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: snippets
      POSTGRES_USER: snippets_user
      POSTGRES_PASSWORD: 1111
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: Snippets.settings
      POSTGRES_DB: snippets
      POSTGRES_USER: snippets_user
      POSTGRES_PASSWORD: 1111
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      ALLOWED_HOSTS: "localhost 127.0.0.1 0.0.0.0"

      GUNICORN_WORKERS: "3"
      GUNICORN_BIND: "0.0.0.0:8000"
      GUNICORN_LOG_LEVEL: "info"
    command: /app/docker/entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: