version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: Snippets.settings
      SECRET_KEY: your-secret-key
      DEBUG: "1"